### ISSUE TITLE
Add build status to the readme file.

### ISSUE THREAD

**Issue by shehand** [scorelab/Ask-SCoRe#26]
Update the readme file with the following content.

[![Build Status](https://github.com/scorelab/Ask-SCoRe/actions/workflows/build.yml/badge.svg?event=pull_request)](https://github.com/scorelab/Ask-SCoRe/actions/workflows/build.yml)

(See the markdown style in order to get the code)

Along with that fix the code quality badge issue also. Seems like the provided repo URL is incorrect.

**Comment by shehand** [comment]
> Update the readme file with the following content.
> 
> [![Build Status](https://github.com/scorelab/Ask-SCoRe/actions/workflows/build.yml/badge.svg?event=pull_request)](https://github.com/scorelab/Ask-SCoRe/actions/workflows/build.yml)
> 
> (See the markdown style in order to get the code)

**Comment by AbhiKul10** [comment]
Okay!
